
project:
  type: website

website:
  title: "Laboratorio 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Aout
      - href: proba.qmd
        text: proba

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
