---
title: "Documentacion Docker"
---

+ Documentacion para crear Docker
  + Crear cuenta en DockerHub en la pagina [ DockerHub ](https://hub.docker.com/)
   
  + Una vez registrados entraremos en la documentacion oficial de Docker parainstalar el docj+¡ker-cli en el enlace [ Instalacion ](https://docs.docker.com/engine/install/ubuntu/)

  +  escribiremos estos comandos 
    
    /* Add Docker's official GPG key:*/
    Sudo apt-get update
    sudo apt-get install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg 
    -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc

    /*Add the repository to Apt sources:*/
    echo \"deb [arch=$(dpkg --print-architecture) 
    signed-by=/etc/apt/keyrings/docker.asc] 
    https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$UBUNTU_CODENAME") 
    stable" | \sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

+ sudo apt-get update  Actualizaremos la lista de paquetes

+ Seguido de la instalacion del Docker-cli con este comando 
  + sudo apt-get install docker-ce docker-ce-cli containerd.io 
  + docker-buildx-plugin docker-compose-plugin

+ Para comprovar que se instalo Docker escribiremos el comando 
  + sudo docker --version

+ Otro comando que se puede ejecutar para asegurarse de que el servicio esta funcionando o para iniciar el sevicio 
  + sudo service docker start


+ Para crear Un contenedor Partiendo de un archivo de spring-boot o de otro framework creare el dockerfile
  + en mi caso hare el contenedor a partir de un ejecutable de sprin-boot

+ en la carpeta donde quiero que contenga el docker creare el archivo app.dockerfile
  + en el archivo tendra que estae este script

    /*Use a Java 21 base image*/
    FROM openjdk:21-jdk-slim

    /*Maintainer information*/
    MAINTAINER PedroCecilia

    /*Copy the application JAR file to the container*/
    COPY BooksPageable-0.0.1-SNAPSHOT.jar books.jar

    /*Set the entry point to run the JAR file*/
    ENTRYPOINT ["java", "-jar", "books.jar"]

+ En la carpeta de docker que contendra el app.dockerfile i el ejecutable de spring-boot.jar ejecutarempos la terminal 

+ Seguido nos loguearemos en DockerHub con el comando 
  + sudo docker login

+ una vez se haia ingresado el codigo temporal que te ofrece en consola hi logueado a trabes de la URL que te da en consola pasaremos a compilar

+ haremos el comando 
  + sudo docker build -f app.dockerfile -t books .

+ unavez compilado ejecutaremos el siguiente comando para iniciar el docker
  + sudo docker run -p 8080:8080 books 



